package io.androllm.core.voice.tts

import android.content.Context
import com.k2fsa.sherpa.onnx.GeneratedAudio
import com.k2fsa.sherpa.onnx.OfflineModelConfig
import com.k2fsa.sherpa.onnx.OfflineTts
import com.k2fsa.sherpa.onnx.OfflineTtsConfig
import com.k2fsa.sherpa.onnx.OfflineTtsModelConfig
import com.k2fsa.sherpa.onnx.OfflineTtsVitsModelConfig
import dagger.hilt.android.qualifiers.ApplicationContext
import io.androllm.core.voice.model.VoiceModels
import javax.inject.Inject
import javax.inject.Singleton
import timber.log.Timber

/**
 * sherpa-onnx offline TTS backend for [OfflineTtsEngine] (VITS).
 *
 * Synthesizes one sentence at a time on a background thread while the next
 * sentence is still being generated by the model — this is what makes the
 * assistant "start speaking immediately" instead of waiting for the whole
 * answer.
 */
@Singleton
class SherpaOnnxOfflineTtsEngine @Inject constructor(
    @ApplicationContext private val context: Context
) : OfflineTtsEngine {

    private var tts: OfflineTts? = null

    override val isInitialized: Boolean get() = tts != null

    override val sampleRate: Int get() = tts?.sampleRate() ?: 22050

    @Synchronized
    override fun ensureInitialized(): Boolean {
        if (tts != null) return true
        val hasAssets = hasAsset(VoiceModels.TTS_MODEL) && hasAsset(VoiceModels.TTS_TOKENS)
        if (!hasAssets) {
            Timber.w("SherpaOnnxOfflineTtsEngine: TTS assets missing")
            return false
        }
        return runCatching {
            val vits = OfflineTtsVitsModelConfig().apply {
                model = VoiceModels.TTS_MODEL
                tokens = VoiceModels.TTS_TOKENS
                lexicon = VoiceModels.TTS_LEXICON
                noiseScale = 0.667f
                noiseScaleW = 0.8f
                lengthScale = 1.0f
            }
            val ttsModel = OfflineTtsModelConfig().apply {
                this.vits = vits
                numThreads = 2
                debug = false
                provider = "cpu"
            }
            val config = OfflineTtsConfig().apply {
                model = ttsModel
                silenceScale = 0.8f
            }
            tts = OfflineTts(context.assets, config)
            true
        }.onFailure { Timber.e(it, "TTS init failed") }.getOrDefault(false)
    }

    /**
     * Synthesizes [text] to a full PCM buffer (mono floats).
     * [speed] is the speaking rate (0.5..2.0). Returns null on failure.
     *
     * The model loads lazily on first use: the assistant spends most of its
     * life listening for the wake word, and pinning the ~114 MB VITS model in
     * RAM 24/7 invites low-memory kills on smaller devices.
     */
    override fun synthesize(text: String, speed: Float): FloatArray? {
        if (text.isBlank()) return null
        if (!ensureInitialized()) return null
        val t = tts ?: return null
        return runCatching {
            // The VITS lexicon has NO digit/symbol tokens — "10 + 10 = 20"
            // otherwise fails as OOV and returns silence. Always convert to
            // natural words first ("ten plus ten equals twenty").
            val spoken = EnglishTtsNormalizer.normalize(text)
            if (spoken.isBlank()) return null
            val audio: GeneratedAudio = t.generate(spoken, 0, speed.coerceIn(0.5f, 2.0f))
            audio.samples
        }.onFailure { Timber.e(it, "TTS synth failed") }.getOrNull()
    }

    @Synchronized
    override fun release() {
        runCatching { tts?.release() }
        tts = null
    }

    private fun hasAsset(path: String): Boolean =
        runCatching { context.assets.open(path).close(); true }.getOrDefault(false)
}