package io.androllm.core.models

import kotlinx.serialization.Serializable

/**
 * Where a message came from. The chat UI uses this to badge voice prompts
 * with a 🎤 icon while still rendering them like any other user message.
 */
@Serializable
enum class MessageOrigin {
    /** Sent from the keyboard / chat input. */
    TYPED,

    /** Captured by the voice assistant after the wake word fired. */
    VOICE,

    /** Generated by an automation (test, debug, importer). */
    AUTOMATION;

    val isVoice: Boolean get() = this == VOICE
}

/**
 * Represents a single message inside a conversation.
 */
@Serializable
data class Message(
    val id: String,
    val conversationId: String,
    val role: MessageRole,
    val content: String,
    val timestamp: Long,
    val isPending: Boolean = false,
    val modelId: String? = null,
    val isBookmarked: Boolean = false,
    /** Source channel — keyboard, voice, etc. Defaults to [MessageOrigin.TYPED]. */
    val origin: MessageOrigin = MessageOrigin.TYPED
)
