package io.androllm.engine.compat

/**
 * Turns raw generated bytes into clean user-facing text for one model family.
 *
 * Responsibilities, in order:
 *  1. UTF-8 decoding that is safe across chunk boundaries (an incomplete
 *     trailing multibyte sequence is held back until the next chunk).
 *  2. Cutting the text at the first family stop sequence.
 *  3. Stripping every family special token (including thinking-channel
 *     markers) so no template garbage can leak into the answer.
 *
 * The family rules come from the [ModelFamilyConfig] — the decoder is the
 * enforcement point of the compatibility contract. Model-specific stop
 * sequences (catalog metadata, container stop tokens) are merged in via
 * [extraStopSequences]; a decoder instance is cheap and stateless apart from
 * the UTF-8 hold-back buffer, so callers can create one per generation.
 */
class OutputDecoder(
    private val config: ModelFamilyConfig,
    extraStopSequences: List<String> = emptyList()
) {

    private val stripTokens: List<String> =
        (config.forbiddenInOutput + listOfNotNull(
            config.thinkingChannel?.start,
            config.thinkingChannel?.end
        )).sortedByDescending { it.length }

    private val stopSequences: List<String> = (config.stopSequences + extraStopSequences)
        .filter { it.isNotBlank() }
        .distinct()
        .sortedByDescending { it.length }

    private var buffer = ByteArray(0)

    fun reset() {
        buffer = ByteArray(0)
    }

    /**
     * Feeds another chunk of generated bytes and returns the clean, decoded
     * text that became available. Incomplete UTF-8 at the end of the chunk is
     * retained until the next call (or [finish]).
     */
    fun feed(bytes: ByteArray): String {
        buffer = buffer + bytes
        val validLength = validUtf8PrefixLength(buffer)
        val text = String(buffer, 0, validLength, Charsets.UTF_8)
        buffer = buffer.copyOfRange(validLength, buffer.size)
        return clean(text)
    }

    /** Flushes any held-back bytes and returns the final clean text. */
    fun finish(): String {
        val text = String(buffer, Charsets.UTF_8)
        buffer = ByteArray(0)
        return clean(text)
    }

    /**
     * Applies the family decode rules to an already-decoded string: cut at the
     * first stop sequence, then strip every special token.
     */
    fun clean(text: String): String {
        var result = text
        var cut = result.length
        for (stop in stopSequences) {
            val idx = result.indexOf(stop)
            if (idx in 0 until cut) cut = idx
        }
        if (cut < result.length) result = result.substring(0, cut)
        for (token in stripTokens) {
            result = result.replace(token, "")
        }
        return result.trim()
    }

    /**
     * Length of the longest prefix of [b] that ends on a UTF-8 code-point
     * boundary. A multibyte sequence that is still incomplete at the end is
     * NOT counted, so the caller can hold it for the next chunk.
     */
    private fun validUtf8PrefixLength(b: ByteArray): Int {
        var i = 0
        while (i < b.size) {
            val c = b[i].toInt() and 0xFF
            val len = when {
                c < 0x80 -> 1
                c and 0xE0 == 0xC0 -> 2
                c and 0xF0 == 0xE0 -> 3
                c and 0xF8 == 0xF0 -> 4
                else -> 1
            }
            if (i + len > b.size) return i
            var valid = true
            for (j in 1 until len) {
                if ((b[i + j].toInt() and 0xC0) != 0x80) {
                    valid = false
                    break
                }
            }
            if (!valid) {
                i++
                continue
            }
            i += len
        }
        return i
    }
}